### ISSUE TITLE
Gitpod kernel dependencies not available

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/template-k3s#1]
### Bug description

The `linux-image-$(uname -r)` (linux-image-5.13.0-1007-gcp) dependency in the .gitpod.yml is no longer available

```bash
$ sudo apt install linux-image-$(uname -r)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package linux-image-5.13.0-1007-gcp
E: Couldn't find any package by glob 'linux-image-5.13.0-1007-gcp'
```

This causes the rest of the preparation steps to fail

### Steps to reproduce

Load up template. Tried is a couple of workspaces, including https://turquoise-bat-kelqgteg.ws-eu25.gitpod.io/

**Comment by aledbf** [comment]
> Unable to locate package linux-image-5.13.0-1007-gcp

The new VM image updates the kernel to `linux-image-5.13.0-1010-gcp`
(to be deployed tomorrow)

**Comment by mrsimonemms** [comment]
Ok, thanks @aledbf

Interestingly, I've tried it with `linux-image-generic` and it seems to work - is this something we could/should use to avoid any future kernel errors?

**Comment by aledbf** [comment]
@MrSimonEmms what you just did, unless there is something related to GCP that you need in the workspace
